language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t eduvzlacerda/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true eduvzlacerda/docker-react npm run test 