language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t eduvzlacerda/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true eduvzlacerda/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-987563775347"
  bucket_path: "react-docker"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY